# Generated by Django 3.0.5 on 2020-06-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200605_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=80),
        ),
    ]
