# Generated by Django 3.0.5 on 2020-05-20 11:46

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200517_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('BE', 'Beaches'), ('IL', 'Ilands'), ('HI', 'Hiking'), ('CA', 'Camping'), ('MO', 'Mountains'), ('DE', 'Deserts'), ('FO', 'Forests'), ('HP', 'Historic Places'), ('MO', 'Monuments'), ('TE', 'Temples'), ('MU', 'Museums'), ('ZO', 'Zoos'), ('TP', 'Theme Parks'), ('GA', 'Gardens'), ('AQ', 'Aquaria'), ('WC', 'Winter Carnival'), ('MA', 'Markets & Shopping'), ('UA', 'Urban'), ('RU', 'Rural'), ('RL', 'Rivers & Lakes'), ('CF', 'Couples Friendly'), ('ST', 'Sports Tourism'), ('JF', 'Just for Food '), ('RE', 'Resorts'), ('CU', 'Culture'), ('AD', 'Adventure')], default='MO', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
