# Generated by Django 3.0.5 on 2020-05-20 11:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200520_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BE', 'Beaches'), ('IL', 'Ilands'), ('HI', 'Hiking'), ('CA', 'Camping'), ('MO', 'Mountains'), ('DE', 'Deserts'), ('FO', 'Forests'), ('HP', 'Historic Places'), ('MO', 'Monuments'), ('TE', 'Temples'), ('MU', 'Museums'), ('ZO', 'Zoos'), ('TP', 'Theme Parks'), ('GA', 'Gardens'), ('AQ', 'Aquaria'), ('WC', 'Winter Carnival'), ('MA', 'Markets & Shopping'), ('UA', 'Urban'), ('RU', 'Rural'), ('RL', 'Rivers & Lakes'), ('CF', 'Couples Friendly'), ('ST', 'Sports Tourism'), ('JF', 'Just for Food '), ('RE', 'Resorts'), ('CU', 'Culture'), ('AD', 'Adventure')], max_length=3),
        ),
    ]
