# Generated by Django 3.0.5 on 2020-05-23 17:56

from django.db import migrations
import djrichtextfield.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200520_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BE', 'Beaches'), ('IL', 'Islands'), ('HI', 'Hiking'), ('CA', 'Camping'), ('MT', 'Mountains'), ('DE', 'Deserts'), ('FO', 'Forests'), ('HP', 'Historic Places'), ('MO', 'Monuments'), ('TE', 'Temples'), ('MU', 'Museums'), ('ZO', 'Zoos'), ('TP', 'Theme Parks'), ('GA', 'Gardens'), ('AQ', 'Aquaria'), ('WC', 'Winter Carnival'), ('MA', 'Markets & Shopping'), ('UA', 'Urban'), ('RU', 'Rural'), ('RL', 'Rivers & Lakes'), ('CF', 'Couples Friendly'), ('ST', 'Sports Tourism'), ('JF', 'Just for Food '), ('RE', 'Resorts'), ('CU', 'Culture'), ('AD', 'Adventure')], max_length=77, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
