# Generated by Django 3.0.5 on 2020-06-08 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_postview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='youtube_channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 12, 12, 54, 991539)),
        ),
    ]
