# Generated by Django 3.0.5 on 2020-06-08 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200608_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('BE', 'Beaches'), ('IL', 'Islands'), ('HI', 'Hiking'), ('CA', 'Camping'), ('MT', 'Mountains'), ('DE', 'Deserts'), ('FO', 'Forests'), ('HP', 'Historic Places'), ('MO', 'Monuments'), ('TE', 'Temples'), ('MU', 'Museums'), ('ZO', 'Zoos'), ('TP', 'Theme Parks'), ('GA', 'Gardens'), ('AQ', 'Aquaria'), ('WC', 'Winter Carnival'), ('MA', 'Markets & Shopping'), ('UA', 'Urban'), ('RU', 'Rural'), ('RL', 'Rivers & Lakes'), ('CF', 'Couples Friendly'), ('ST', 'Sports Tourism'), ('JF', 'Just for Food '), ('RE', 'Resorts'), ('CU', 'Culture'), ('AD', 'Adventure'), ('MB', 'Moto Blogs'), ('ST', 'Solo Travel'), ('SS', 'Summer Special')], max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.CharField(choices=[('II', 'Somewhere In India'), ('OI', 'Out Of India'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CT', 'Chhattisgarh'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Orissa'), ('PB', 'Punjab'), ('PY', 'Pondicherry'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal')], max_length=80),
        ),
        migrations.AlterField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 15, 48, 19, 602326)),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='post_category', to='blog.Category'),
        ),
    ]
