# Generated by Django 3.0.5 on 2020-06-08 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200608_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, choices=[('0', 'Beaches'), ('1', 'Islands'), ('2', 'Hiking'), ('3', 'Camping'), ('4', 'Mountains'), ('5', 'Deserts'), ('6', 'Forests'), ('7', 'Historic Places'), ('8', 'Monuments'), ('9', 'Temples'), ('10', 'Museums'), ('11', 'Zoos'), ('12', 'Theme Parks'), ('13', 'Gardens'), ('14', 'Aquaria'), ('15', 'Winter Carnival'), ('16', 'Markets & Shopping'), ('17', 'Urban'), ('18', 'Rural'), ('19', 'Rivers & Lakes'), ('20', 'Couples Friendly'), ('21', 'Sports Tourism'), ('22', 'Just for Food '), ('23', 'Resorts'), ('24', 'Culture'), ('25', 'Adventure'), ('26', 'Moto Blogs'), ('27', 'Solo Travel'), ('28', 'Summer Special')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 16, 24, 4, 72346)),
        ),
    ]
