# Generated by Django 3.0.5 on 2020-06-08 13:40

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0019_auto_20200608_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, choices=[('Beaches ', 'Beaches'), ('Islands ', 'Islands'), ('Hiking', 'Hiking'), ('Camping ', 'Camping'), ('Mountains ', 'Mountains'), ('Deserts ', 'Deserts'), ('Forests ', 'Forests'), ('Historic Places ', 'Historic Places'), ('Monuments ', 'Monuments'), ('Temples ', 'Temples'), ('Museums ', 'Museums'), ('Zoos ', 'Zoos'), ('Theme Parks ', 'Theme Parks'), ('Gardens ', 'Gardens'), ('Aquaria ', 'Aquaria'), ('Winter ', 'Winter Carnival'), ('Markets & Shopping ', 'Markets & Shopping'), ('Urban ', 'Urban'), ('Rural ', 'Rural'), ('Rivers & Lakes ', 'Rivers & Lakes'), ('Couples Friendly ', 'Couples Friendly'), ('Sports Tourism ', 'Sports Tourism'), ('Just for Food ', 'Just for Food '), ('Resorts ', 'Resorts'), ('Culture ', 'Culture'), ('Adventure ', 'Adventure'), ('Moto Blogs ', 'Moto Blogs'), ('Solo ', 'Solo Travel'), ('Summer ', 'Summer Special')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='post_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 19, 10, 50, 403254)),
        ),
    ]
