# Generated by Django 3.0.5 on 2020-06-11 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200612_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, choices=[('Beaches', 'Beaches'), ('Islands', 'Islands'), ('Hiking', 'Hiking'), ('Camping', 'Camping'), ('Mountains', 'Mountains'), ('Deserts', 'Deserts'), ('Forests', 'Forests'), ('Historic-Places', 'Historic-Places'), ('Monuments', 'Monuments'), ('Temples', 'Temples'), ('Museums', 'Museums'), ('Zoos', 'Zoos'), ('Theme-Parks', 'Theme-Parks'), ('Gardens', 'Gardens'), ('Aquaria', 'Aquaria'), ('Winter', 'Winter Carnival'), ('Market-Shopping', 'Market-Shopping'), ('Urban', 'Urban'), ('Rural', 'Rural'), ('Rivers-Lakes', 'Rivers-Lakes'), ('Couples-Friendly', 'Couples Friendly'), ('Sports-Tourism', 'Sports-Tourism'), ('Just4Food', 'Just4Food '), ('Resorts', 'Resorts'), ('Culture', 'Culture'), ('Adventure', 'Adventure'), ('Moto-Blogs', 'Moto-Blogs'), ('Solo', 'Solo'), ('Summer', 'Summer'), ('Travel-Tips', 'Travel-Tips')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 0, 13, 29, 362692)),
        ),
    ]
