# Generated by Django 3.0.5 on 2020-06-11 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200612_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, choices=[('Beaches', 'Beaches'), ('Islands', 'Islands'), ('Hiking', 'Hiking'), ('Camping', 'Camping'), ('Mountains', 'Mountains'), ('Deserts', 'Deserts'), ('Forests', 'Forests'), ('Historic', 'Historic'), ('Monuments', 'Monuments'), ('Temples', 'Temples'), ('Museums', 'Museums'), ('Zoos', 'Zoos'), ('ThemeParks', 'ThemeParks'), ('Gardens', 'Gardens'), ('Aquaria', 'Aquaria'), ('Winter', 'Winter'), ('Market', 'Market'), ('Urban', 'Urban'), ('Rural', 'Rural'), ('Rivers', 'Rivers'), ('Lakes', 'Lakes'), ('Couple', 'Couple'), ('Sports', 'Sports'), ('Food', 'Food '), ('Resorts', 'Resorts'), ('Culture', 'Culture'), ('Adventure', 'Adventure'), ('MotoBlogs', 'MotoBlogs'), ('Solo', 'Solo'), ('Summer', 'Summer'), ('TravelTips', 'TravelTips')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 0, 19, 55, 634706)),
        ),
    ]
