# Generated by Django 3.0.5 on 2020-06-11 19:26

import autoslug.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200612_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_st',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='state'),
        ),
        migrations.AlterField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 0, 56, 17, 365698)),
        ),
    ]
