# Generated by Django 3.0.5 on 2020-06-13 06:31

import autoslug.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200612_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_lc',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='location'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_st',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='state'),
        ),
        migrations.AlterField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 12, 1, 20, 39709)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
