# Generated by Django 3.0.5 on 2020-06-15 05:48

import autoslug.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200613_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug_lc',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='location'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 11, 18, 19, 383540)),
        ),
    ]
