# Generated by Django 3.0.5 on 2020-06-15 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20200615_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 15, 59, 54, 890404)),
        ),
    ]
