# Generated by Django 3.0.5 on 2020-06-20 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20200620_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 11, 53, 5, 403277)),
        ),
    ]
